# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.7"
    # You can also specify other tool versions:
    nodejs: "18"
    # rust: "1.64"
    # golang: "1.19"
  jobs:
    post_checkout:
      # Unshallow the git repository to
      # have access to its full history
      - pip install --force-reinstall "numpy<=1.21.5"
#  commands:
#    - pip install --force-reinstall "numpy<=1.21.5"
#    - cd docs/ # && npm install
    # Build the site
    # - cd docs/ && npm run build
    # Copy generated files into Read the Docs directory
#    - mkdir --parents _readthedocs/html/
    # - cp --recursive docs/build/* _readthedocs/html/
    #  apt_packages:
#    - build-essential
#    - make
#    - llvm

    # Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally declare the Python requirements required to build your docs
python:
  system_packages: true
  install:
   - requirements: docs/requirements.readthedocs.txt