# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"
  apt_packages:
    - build-essential
    - libssl-dev
      zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - curl
    - libncursesw5-dev
    - xz-utils tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
formats:
  - pdf

# Optionally declare the Python requirements required to build your docs
python:
  system_packages: true
  install:
   - requirements: docs/requirements.readthedocs.txt