language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"

branches:
  only:
    - master
    - development_abel

notifications:
  email:
  - abelcarreras83@gmail.com
#  - komuisan@gmail.com

install:
    - sudo apt-get install libblas-dev liblapack-dev
    - sudo apt-get install gfortran
    - pip install coverage
    - pip install python-coveralls
    - pip install -r requirements.txt
    - pip install -e .

script:
    - cd tests
    - coverage run --source=../symeess -m unittest discover . "test_*.py"

after_success:
    - coveralls
    - cd ..

deploy:
  - provider: pypi
    distributions: sdist
    user: abelcarreras83
    password:
      secure: "Tphu8lShIDsMiR+HQR26G/CCPDt4Xvi9LBYye9BcNYGBn9l3gdg5pQk0bBCNYI3g53IXkJjdYqkGPaBUT/6b5rs7YH8Bft3D8jUxtpXu7riQwgKv7XKl8IkHB24ETmiZqFxAUmMFGUwKSVK+0Oz4wcKSct2M0gA5mxcDINHRmd0kcjIltEY2EKHX+OX3V+0sDfkP3gUka8O8Ib7LO0ssANl5eoY6lB7MDcQ1J1334KkMxKjEZQzh33gx5Prn9NicbpnGIZ+hQy77QtvYsD+2ajfi2Zbvw7glC71a2Dq9+ebwoVUpThDZdjxi/ViRFVd75eXNfPv5iJpYJ1U9Km7RMUsus8yOCSx3/GMQERGvk8RBy0G/bJQPb8pwhC5rPjYpkZCzu3RLpl66vuOH/4S9G0An47UhAOERCVyuzN6cwogJGoieSTBki+SvpqD5zlPYeC/GuZD/KqplgZVnrDo6UDt9Dm8h2h34ZdF2cD6/SCdjD54XoBJY+rpuFZREYRyVxuKIJDRJ1v1+vbxzhX1abBgPbRFml3jSZ6JotOWs7TVy05jNseAL7koPNskdWGQFqsKhmbhykiJvJHADiDumMQe/Cdg++xxqMBa7/o/1SjdNH1jcNeQjXIHzpHP7LwM67lRShY6nObtmFtm24kaJ34E7YHmKwMg6fo63E5Hnaws="
    skip_existing: true
    on:
      branch: development_abel
      tags: false